# Generated by Django 3.1.7 on 2021-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_categorypost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Данные из чата',
                'verbose_name_plural': 'Данные из чата',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория для Прошивки', 'verbose_name_plural': 'Категории для Прошивок'},
        ),
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Категории для Статьи', 'verbose_name_plural': 'Категории для Статей'},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'verbose_name': 'Прошивка', 'verbose_name_plural': 'Прошивки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Технология подключения', 'verbose_name_plural': 'Технологии подключения'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
